### ISSUE TITLE
J23,  rotor lock function jumpers and display options

### ISSUE THREAD

**Issue by ghost** [bigtreetech/BIGTREETECH-SKR-CR6#18]
What is J23 for?

Which of the stepper driver  jumpers are for X and Y. I only want to enable the lock rotor detection function on X and Y.

I see RX1/TX1 and RX2/TX2 on the port for the original display. I guess these are 2 independant serial port? If using 12864 then I can use both of these? are  they separate from the TFT serial port?

Using both original and 12864 displays at the same time would be just enabling both in the configuration.h no?

**Comment by ghost** [comment]
all solved.

**Comment by gulliver103** [comment]
Hi badbod!
What is J23 for?
Can it be used as an extra port to connect to octoprint?
Regards /Gulliver

**Comment by ghost** [comment]
no, J23 is still a mystery ,  you can get serial for octoprint from the TFT port (if your not using it for a TFT)  RX2/TX2 or the RX1/TX1  of the EXP port  whichever your not using for a display.   Currently using the TFT port for both power and serial for bananapi BPIM2-ZERO-2 with klipper. very neat solution without all the usual PSU and.usb etc cabling PI spaghetti. Onviously only really works if the antenna can make it's way out or the case has plastic front panel or something or your wifi wont get far out of the printer if it is all metal enclosure.  whiel a PI Zero2 does nto have the power for octoprint/Marlin  a BPIM2-ZERO-2 does, in the same form factor.

**Comment by Dalber85** [comment]
Hi badbod I was hoping you could help me I've got Klipper firmware up and running in my CR6se with BTT SKR-CR6 main board in the printer and a raspberry pi 3b running klipper with mainsailos but that is all using USB to connect the printer to the PI , I need help on making a new firmware.bin file so that I can use the TFT pins to power my pi and provide communication between my PI and my printer but I don't know what to select in makemenuconfig to use those pins I know is uart I think but I would greatly appreciate you guidance since it looks like you use it successfully with a bananaPI feel free to email me directly if you wish maybe your firmware.bin file will work for me 

Dalber85@gmail.com
